import type { TenantTheme } from "@/lib/tenant-theme";

/**
 * Hand-tuned theme presets, keyed by tenant slug. A preset wins over the
 * theme derived from the tenants table so flagship tenants get exact,
 * art-directed palettes; tenants without a preset fall back to deriveTheme().
 */
export const TENANT_THEME_PRESETS: Record<string, TenantTheme> = {
  // TAV Airports — the original Employee Atlas palette (Pantone 2748C
  // midnight, 2727C sky). Identical to the globals.css defaults so the TAV
  // workspace looks exactly as it did before multi-tenancy.
  "tav-airports": {
    "--background": "#f7f9fc",
    "--foreground": "#1a2233",
    "--card": "#ffffff",
    "--card-foreground": "#1a2233",
    "--popover": "#ffffff",
    "--popover-foreground": "#1a2233",
    "--primary": "#031f73",
    "--primary-foreground": "#ffffff",
    "--secondary": "#ebf1fa",
    "--secondary-foreground": "#031f73",
    "--muted": "#eef2f8",
    "--muted-foreground": "#5b6b85",
    "--accent": "#e4eefb",
    "--accent-foreground": "#031f73",
    "--border": "#e3e9f2",
    "--input": "#d7dfec",
    "--ring": "#307fe2",
    "--sky": "#307fe2",
    "--sky-foreground": "#ffffff",
    "--chart-1": "#031f73",
    "--chart-2": "#307fe2",
    "--chart-3": "#faa634",
    "--chart-4": "#48d8ac",
    "--chart-5": "#4fc6e0",
    "--chart-6": "#5c2885",
    "--chart-7": "#688587",
    "--chart-8": "#e3a9c3",
    "--sidebar": "#031f73",
    "--sidebar-foreground": "#c6d4ee",
    "--sidebar-primary": "#307fe2",
    "--sidebar-primary-foreground": "#ffffff",
    "--sidebar-accent": "rgba(255, 255, 255, 0.08)",
    "--sidebar-accent-foreground": "#ffffff",
    "--sidebar-border": "rgba(255, 255, 255, 0.12)",
    "--sidebar-ring": "#307fe2",
    "--tenant-primary": "#031f73",
    "--tenant-secondary": "#307fe2",
    "--tenant-accent": "#faa634",
    "--tenant-bg": "#f7f9fc",
    "--tenant-text": "#1a2233",
    "--tenant-muted": "#eef2f8",
  },

  // Turkcell — telecom enterprise: deep cool blue surfaces, near-black-blue
  // sidebar, signature yellow reserved for active states and chart accents.
  turkcell: {
    "--background": "#f6f9fb",
    "--foreground": "#142433",
    "--card": "#ffffff",
    "--card-foreground": "#142433",
    "--popover": "#ffffff",
    "--popover-foreground": "#142433",
    "--primary": "#00457c",
    "--primary-foreground": "#ffffff",
    "--secondary": "#e7f1f8",
    "--secondary-foreground": "#00457c",
    "--muted": "#edf2f6",
    "--muted-foreground": "#55697d",
    "--accent": "#e0eef8",
    "--accent-foreground": "#00457c",
    "--border": "#dfe7ee",
    "--input": "#d3dee8",
    "--ring": "#0082ca",
    "--sky": "#0082ca",
    "--sky-foreground": "#ffffff",
    "--chart-1": "#00457c",
    "--chart-2": "#0082ca",
    "--chart-3": "#ffc900",
    "--chart-4": "#00a5a8",
    "--chart-5": "#7ab8e0",
    "--chart-6": "#5b6b85",
    "--chart-7": "#c98a00",
    "--chart-8": "#9bc4d8",
    "--sidebar": "#002b4e",
    "--sidebar-foreground": "#b7cde2",
    "--sidebar-primary": "#ffc900",
    "--sidebar-primary-foreground": "#002b4e",
    "--sidebar-accent": "rgba(255, 255, 255, 0.08)",
    "--sidebar-accent-foreground": "#ffffff",
    "--sidebar-border": "rgba(255, 255, 255, 0.12)",
    "--sidebar-ring": "#ffc900",
    "--tenant-primary": "#00457c",
    "--tenant-secondary": "#0082ca",
    "--tenant-accent": "#ffc900",
    "--tenant-bg": "#f6f9fb",
    "--tenant-text": "#142433",
    "--tenant-muted": "#edf2f6",
  },

  // Grup 43 — bootcamp documentation workspace. A calm indigo/slate scheme
  // with an emerald accent, deliberately distinct from the customer tenants
  // so it reads as an internal docs panel rather than a product workspace.
  "grup-43": {
    "--background": "#f8fafc",
    "--foreground": "#0f172a",
    "--card": "#ffffff",
    "--card-foreground": "#0f172a",
    "--popover": "#ffffff",
    "--popover-foreground": "#0f172a",
    "--primary": "#4338ca",
    "--primary-foreground": "#ffffff",
    "--secondary": "#eef2ff",
    "--secondary-foreground": "#4338ca",
    "--muted": "#f1f5f9",
    "--muted-foreground": "#64748b",
    "--accent": "#e0e7ff",
    "--accent-foreground": "#4338ca",
    "--border": "#e2e8f0",
    "--input": "#cbd5e1",
    "--ring": "#6366f1",
    "--sky": "#6366f1",
    "--sky-foreground": "#ffffff",
    "--chart-1": "#4338ca",
    "--chart-2": "#6366f1",
    "--chart-3": "#f59e0b",
    "--chart-4": "#10b981",
    "--chart-5": "#818cf8",
    "--chart-6": "#64748b",
    "--chart-7": "#c2410c",
    "--chart-8": "#a5b4fc",
    "--sidebar": "#1e1b4b",
    "--sidebar-foreground": "#c7d2fe",
    "--sidebar-primary": "#818cf8",
    "--sidebar-primary-foreground": "#1e1b4b",
    "--sidebar-accent": "rgba(255, 255, 255, 0.08)",
    "--sidebar-accent-foreground": "#ffffff",
    "--sidebar-border": "rgba(255, 255, 255, 0.12)",
    "--sidebar-ring": "#818cf8",
    "--tenant-primary": "#4338ca",
    "--tenant-secondary": "#6366f1",
    "--tenant-accent": "#10b981",
    "--tenant-bg": "#f8fafc",
    "--tenant-text": "#0f172a",
    "--tenant-muted": "#f1f5f9",
  },
};
